// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn4A0YdtMowpCHSMiKJPm1YBZAfJdzYlY',
    appId: '1:630937084600:web:f815b82b90eb554a3e4a4d',
    messagingSenderId: '630937084600',
    projectId: 'bookly-app-ff124',
    authDomain: 'bookly-app-ff124.firebaseapp.com',
    storageBucket: 'bookly-app-ff124.firebasestorage.app',
    measurementId: 'G-9Q7M6FJXJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAksU1gRPomuXoNu14HJwdR908OSjM8Kg',
    appId: '1:630937084600:android:d91cf4478c6084553e4a4d',
    messagingSenderId: '630937084600',
    projectId: 'bookly-app-ff124',
    storageBucket: 'bookly-app-ff124.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd0g8-BNuSoH3hHOIUygBgD-r3V55S9cU',
    appId: '1:630937084600:ios:9d6f40f5239342413e4a4d',
    messagingSenderId: '630937084600',
    projectId: 'bookly-app-ff124',
    storageBucket: 'bookly-app-ff124.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn4A0YdtMowpCHSMiKJPm1YBZAfJdzYlY',
    appId: '1:630937084600:web:4cd4b8c0550e92033e4a4d',
    messagingSenderId: '630937084600',
    projectId: 'bookly-app-ff124',
    authDomain: 'bookly-app-ff124.firebaseapp.com',
    storageBucket: 'bookly-app-ff124.firebasestorage.app',
    measurementId: 'G-SD8ZK1593N',
  );

}